name: notify action

on:
  push: #监听事件
    branches:
      - master #推送分支

env: # 设置环境变量
  TZ: Asia/Shanghai
  GIT_USER: soloveri
  GIT_EMAIL: 13207148685@163.com
  NOTE_REPO: soloveri/notes-of-cs
  NOTE_BRANCH: master
  BLOG_REPO: soloveri/blog
  BLOG_BRANCH: master
  NOTIFY_FILE: date.txt

jobs:
  update_date:
    runs-on: ubuntu-latest
    steps:

    - name: save current date
    run: |
      date > ${{ env.NOTIFY_FILE }}   

    - name: Pushes date file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.BLOG_TOKEN }}
      with:
        source_file: ${{ env.NOTIFY_FILE }}
        destination_repo: ${{ env.BLOG_REPO }}
        destination_branch: ${{ env.BLOG_BRANCH }}
        user_email: ${{ env.GIT_USER }}
        user_name: ${{ env.GIT_USER }}
        commit_message: 'A auto action for the commit'